# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-24 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0002_auto_20191024_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, default='settings.MEDIA_ROOT/default_image.png', null=True, upload_to=''),
        ),
    ]
